name: iOS Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'App/**'
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CocoaPods dependencies
        run: |
          cd App
          pod install

      - name: Extract version info
        id: version
        run: |
          VERSION=$(grep -oE 'MARKETING_VERSION = [^;]+' App/App.xcodeproj/project.pbxproj | head -1 | sed 's/MARKETING_VERSION = //;s/;//;s/ //g;s/"//g')
          BUILD=$(grep -oE 'CURRENT_PROJECT_VERSION = [^;]+' App/App.xcodeproj/project.pbxproj | head -1 | sed 's/CURRENT_PROJECT_VERSION = //;s/;//;s/ //g;s/"//g')
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IPA_NAME="BeautyCita-iOS-v${VERSION}-Build${BUILD}-${TIMESTAMP}.ipa"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "build=${BUILD}" >> $GITHUB_OUTPUT
          echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "ipa_name=${IPA_NAME}" >> $GITHUB_OUTPUT

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS app
        run: |
          cd App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $RUNNER_TEMP/BeautyCita.xcarchive \
            clean archive

      - name: Export IPA
        run: |
          cd App
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/BeautyCita.xcarchive \
            -exportPath $RUNNER_TEMP \
            -exportOptionsPlist ExportOptions.plist || echo "Export failed - may need signing"

          if [ -f "$RUNNER_TEMP/App.ipa" ]; then
            mv $RUNNER_TEMP/App.ipa $RUNNER_TEMP/${{ steps.version.outputs.ipa_name }}
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BeautyCita-iOS-Archive
          path: ${{ runner.temp }}/BeautyCita.xcarchive
          retention-days: 5

      - name: Build summary
        if: always()
        run: |
          echo "## Build Results" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Build:** ${{ steps.version.outputs.build }}" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** ${{ steps.version.outputs.timestamp }}" >> $GITHUB_STEP_SUMMARY
